version: '3.1'

services:
  banco:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=ROOT@123
      - MARIADB_DATABASE=ponto
      - MARIADB_USER=ponto
      - MARIADB_PASSWORD=PONTO@123
    volumes:
      - ./ponto_db:/var/lib/mysql
    ports:
      - 13306:3306